#soon ...
#sudo: false
language: python
python:
    - "2.7"
env:
    - CKANVERSION=inventory
install:
    - bash bin/travis-build.bash
script: sh bin/travis-run.sh
after_success:
    - coveralls
notifications:
  email:
    on_success: never  # default: change
    on_failure: always # default: always